
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres4
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: rails_course_development4
test:
  <<: *default
  database: rails_course_test4
production:
  <<: *default
  database: rails_course_production4
  username: rails_course4
  password: <%= ENV['RAILS_COURSE_DATABASE_PASSWORD'] %>
